language: node_js
node_js:
- '4.0'
- '9.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: kQQDqQBicITH6D5Rg9CBNt2qD/CMsnW9eWDS8gHJkvkJIcHThxQgC0++nnAXv+CViCgIwKOTbS1PvOOJh5ENS2CT/1YjhXm/jfNNI8TKmFMUUSfg29xvW+EGLWUaMoXsORebdJzkd/m4iIwAF/QlBvIypQGzMJ7a77elcy1FWI4+7pTqo8RYwKM51CD/bpDlp0rYloa9zmp5mfMjWumgL0vsmycNZJZ6eQVDtP5OEM1/aN7FG/tkEa/lKmaOB9E07S8idx5bPK6r3zhyrgli02NjLJcMDwtQsdJwuPMypaCpRsTvWv4NS6vs6hHJmsx3Cm05rPhUyPMTyEM0T1u8XPk/ZEJKDuwEEIiOwQpq7VbYQNOaPvmSfa0tChnooXlv65RN2jiS0M8zqfdMhUtVVcvonP0HjqF2R+obny1UdPymPb5x4jsXTKEsFLY7SuZg0wQ3UyCvwMN6U2vhBrKvFz5iBsUrVSBLOrGzetzn1xVGMTUED6Rm9c7wez9g+SevzLZqs1uewgNHTXdLoQamf47FitMzcOD1+v5zpjWAY76coyUIaADdRsIR0I1Ga9XQvoa7lNerp83lBs8SNAoVs4g58N3EkRcdH+kYk2MJqkUeX/WPspxjia10zz0GMiyPgcQNuuhiCvt66Fcoha167YG4AOmBXkWi8ISF1OxI+x4=
  file:
    - "unist-util-visit-children.js"
    - "unist-util-visit-children.min.js"
  on:
    tags: true
    node: '9.0'
