language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: AibpxnmOOUzDpxJPbFivN5kKUNNP5H4xxfvjYaJPUgzWtscoQzI30TBSSIAgczb8RXa7cEIut5swKi797grvLlfxQeDTAhrnfPFhlL8mLOztgvgW4Rh54q/6iXCXE7kYhlFC9ULJb7aC0Hn3wkjU2AsmlJuw2vrBjL6eFOHJEIhY5OM5wqaWdKjY6/Pv0WlhjAQHVretvdWAc6i2xjHFo9IemmDeACpBsD1qd0FFqZMvewZhWgBbFuT8zYG8EKZm3HgTcZgLs6Occxy8tMkpBgSUdhpAVLq2D/RkmFF/aV4R6d42gUdT5sAGJp02yF/ISPbLZ/zYFnhbW10EQ5vtyrC2kkZ9d34+TUCZMrRLyV04v3o5gFMWVou+MpTet8RmditQJKn5cmLzbxNxQTeo9JLvZOUhQ6UdmV+7OCJs1159xl56HFCDMzMpA+qQXnHy7jPtdBgH2Pl3gc7rUtyNZ1yaYAgfIY1OfsB/qscdZoDVWKEy48u9JxN4GkSqlsLh/ZzDrjHv5wMC5rizBwb98g+UckfNBp6AHs49NHBUde0Ll8WvZLf3fFhrfBljZ9ryQSum82W1NHTPf5hywE14ZpUjL5kgtggLJOtbU8Jex9lu5ju1qPsfovJIHb/qxISxXQcs6FpIbYJffvMCpYb6CIU/2qrTQeH9v9m0VGqlAIc=
  file:
    - 'unist-util-visit-children.js'
    - 'unist-util-visit-children.min.js'
  on:
    tags: true
